% startup

%% Setup path
MyPath.Root = fullfile(pwd,'Matlab/');
MyPath.List = {...
    'vcDSGE',...
    'vcTools',...
    'Misc',...
    'Misc/SimsGensys',...
    'Misc/SimsKF',...
    'Misc/SimsOptimize',...
    'Misc/SimsVARtools',...
    'Misc/JaeWon',...
    };
for j=1:length(MyPath.List)
    MyPath.Add{j} = [MyPath.Root,MyPath.List{j}];
end
addpath(MyPath.Add{:})

%% change text interpreter
set(groot,'defaultTextInterpreter','latex');
set(groot,'defaultLegendInterpreter','latex');

